# Generated by Django 6.0.7 on 2026-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='حظر العميل من إنشاء رحلات جديدة'),
        ),
    ]
