# Generated by Django 6.0.7 on 2026-07-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_price_per_liter', models.DecimalField(decimal_places=2, default=22.25, max_digits=6)),
                ('platform_percent', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('fuel_percent', models.DecimalField(decimal_places=2, default=36.0, max_digits=5)),
                ('maintenance_percent', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('driver_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('fuel_efficiency', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات التسعير',
                'verbose_name_plural': 'إعدادات التسعير',
            },
        ),
    ]
