# Generated by Django 6.0.7 on 2026-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='platform_wallet_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
