# Generated by Django 6.0.7 on 2026-07-11 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('car', 'نقل أشخاص'), ('pickup_truck', 'نقل ثقيل (بيك أب)'), ('refrigerated_truck', 'نقل مبرد'), ('motorcycle', 'توصيل بالموتوسيكل')], max_length=30)),
                ('pickup_address', models.CharField(max_length=255)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'بانتظار كابتن'), ('accepted', 'تم القبول'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('platform_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('driver_profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_customer', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
