# Generated by Django 6.0.7 on 2026-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='trip',
            name='commission_settled',
            field=models.BooleanField(default=False, help_text='هل تم تسجيل عمولة المنصة كمديونية على الكابتن (لرحلات الكاش)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='estimated_duration_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('wallet', 'محفظة إلكترونية')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'لم يتم الدفع بعد'), ('proof_uploaded', 'بانتظار مراجعة الإدارة'), ('confirmed', 'تم تأكيد الدفع')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='price_increase_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='wallet_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
