# Generated by Django 6.0.7 on 2026-07-11 15:12

import django.db.models.deletion
import drivers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('private_car', 'سيارة خاصة'), ('pickup_truck', 'سيارة نقل (بيك أب)'), ('refrigerated_truck', 'شاحنة مبردة'), ('motorcycle', 'موتوسيكل توصيل')], max_length=30)),
                ('vehicle_photo', models.ImageField(upload_to=drivers.models.driver_doc_path)),
                ('license_photo', models.ImageField(upload_to=drivers.models.driver_doc_path)),
                ('id_selfie_front', models.ImageField(help_text='صورة شخصية ممسكاً البطاقة من ناحية الوش', upload_to=drivers.models.driver_doc_path)),
                ('id_photo_back', models.ImageField(help_text='صورة ظهر البطاقة الشخصية', upload_to=drivers.models.driver_doc_path)),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب انضمام كابتن',
                'verbose_name_plural': 'طلبات انضمام الكباتن',
                'ordering': ['-created_at'],
            },
        ),
    ]
