# Generated by Django 6.0.7 on 2026-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverapplication',
            name='debt_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='إجمالي عمولة المنصة المستحقة على الكابتن من رحلات الكاش غير المسددة', max_digits=8),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='debt_limit',
            field=models.DecimalField(decimal_places=2, default=200, help_text='الحد الأقصى للمديونية قبل إيقاف استقبال طلبات جديدة', max_digits=8),
        ),
    ]
